### ISSUE TITLE
Is this module safe with python 3.8?

### ISSUE THREAD

**Issue by alex-eri** [segevfiner/sslkeylog#3]
At this commit added keylog support to python
https://github.com/python/cpython/commit/c7f7069e77c58e83b847c0bfe4d5aadf6add2e68

But i need to get master key, not log.

**Comment by segevfiner** [comment]
When using SSL versions that do use a master key (TLS <= 1.2) you can use `get_master_key` and pass it the socket.

The module also supports specifying your own callback function in `set_keylog` that is called whenever keying material such as a master key is created (On handshake).

This module is similar in that regard to the commit you linked and is an implementation of it for current Python versions that don't have this builtin. Though the bulit-in feature only supports a file. You might want to open an issue or ping Python's mailing list if you want to see the future builtin feature improved.
