### ISSUE TITLE
Perhaps link the source in docs

### ISSUE THREAD

**Issue by nyov** [segevfiner/sslkeylog#5]
I had a slightly hard time getting from here https://sslkeylog.readthedocs.io/ to here https://github.com/segevfiner/sslkeylog, as the docs don't mention any kind of source (or pypi) url.

At least a hint might be good. ;)

**Comment by segevfiner** [comment]
There is the "star" button which leads to GitHub, but maybe this needs more obvious links in the sidebar or somewhere at the top.

**Comment by nyov** [comment]
Ah! Apologies, I should remember to check my javascript site settings before making such claims. Feel free to consider this resolved, thanks. Ouch ;)
